apiVersion: v1
kind: Service
metadata:
  name: apps-programmes-api
  labels:
    app: apps-programmes-api
spec:
  clusterIP: None
  selector:
    app: apps-programmes-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-programmes-api
  labels:
    app: apps-programmes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-programmes-api
  template:
    metadata:
      labels:
        app: apps-programmes-api
    spec:
      containers:
      - name: apps-programmes-api
        image: apps-programmes-api
