apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: programmes-api
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: programmes-api
      docker:
        dockerfile: ./Dockerfile
  local:
    push: false
    useBuildkit: true

manifests:
   kustomize:
      paths:
       - k8s/dev
deploy:
  kubectl: {}

profiles:
  - name: staging
    manifests:
      kustomize:
        paths:
          - k8s/staging