apiVersion: v1
kind: Service
metadata:
  name: apps-nx-demo
  labels:
    app: apps-nx-demo
spec:
  clusterIP: None
  selector:
    app: apps-nx-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-nx-demo
  labels:
    app: apps-nx-demo
spec:
  replicas: {{ .Values.nx_demo.replicaCount }}
  selector:
    matchLabels:
      app: apps-nx-demo
  template:
    metadata:
      labels:
        app: apps-nx-demo
    spec:
      containers:
      - name: apps-nx-demo
        image: "{{.Values.nx_demo.image.repository }}:{{ default .Chart.AppVersion .Values.nx_demo.image.tag }}"

